rename sonic1\grnhill.mid grnhill.mid
rename sonic1\labyrint.mid labyrint.mid
rename sonic1\marble.mid marble.mid
rename sonic1\s1_ss.mid s1_ss.mid
rename sonic1\scrap.mid scrap.mid
rename sonic1\son1bos1.mid son1bos1.mid
rename sonic1\final.mid final.mid
rename sonic1\son1end.mid son1end.mid
rename sonic1\spryard.mid spryard.mid
rename sonic1\starlite.mid starlite.mid
rename sonic1\grnhill.htm grnhill.htm
rename sonic1\labyrint.htm labyrint.htm
rename sonic1\marble.htm marble.htm
rename sonic1\s1_ss.htm s1_ss.htm
rename sonic1\scrap.htm scrap.htm
rename sonic1\son1bos1.htm son1bos1.htm
rename sonic1\final.htm final.htm
rename sonic1\son1end.htm son1end.htm
rename sonic1\spryard.htm spryard.htm
rename sonic1\starlite.htm starlite.htm
rename sonic2\casino.mid casino.mid
rename sonic2\casino2p.mid casino2p.mid
rename sonic2\chmplant.mid chmplant.mid
rename sonic2\deathegg.mid deathegg.mid
rename sonic2\emrld2p.mid emrld2p.mid
rename sonic2\emrldhil.mid emrldhil.mid
rename sonic2\hidden_p.mid hidden_p.mid
rename sonic2\hilltop.mid hilltop.mid
rename sonic2\metropol.mid metropol.mid
rename sonic2\mstcave2.mid mstcave2.mid
rename sonic2\mystic.mid mystic.mid
rename sonic2\oilocean.mid oilocean.mid
rename sonic2\raceres.mid raceres.mid
rename sonic2\s2_ss.mid s2_ss.mid
rename sonic2\s2option.mid s2option.mid
rename sonic2\aquaticr.mid aquaticr.mid
rename sonic2\skychase.mid skychase.mid
rename sonic2\son2bos1.mid son2bos1.mid
rename sonic2\son2boss.mid son2boss.mid
rename sonic2\son2end.mid son2end.mid
rename sonic2\son2end2.mid son2end2.mid
rename sonic2\superson.mid superson.mid
rename sonic2\wingfort.mid wingfort.mid
rename sonic2\casino.htm casino.htm
rename sonic2\casino2p.htm casino2p.htm
rename sonic2\chmplant.htm chmplant.htm
rename sonic2\deathegg.htm deathegg.htm
rename sonic2\emrld2p.htm emrld2p.htm
rename sonic2\emrldhil.htm emrldhil.htm
rename sonic2\hidden_p.htm hidden_p.htm
rename sonic2\hilltop.htm hilltop.htm
rename sonic2\metropol.htm metropol.htm
rename sonic2\mstcave2.htm mstcave2.htm
rename sonic2\mystic.htm mystic.htm
rename sonic2\oilocean.htm oilocean.htm
rename sonic2\raceres.htm raceres.htm
rename sonic2\s2_ss.htm s2_ss.htm
rename sonic2\s2option.htm s2option.htm
rename sonic2\aquaticr.htm aquaticr.htm
rename sonic2\skychase.htm skychase.htm
rename sonic2\son2bos1.htm son2bos1.htm
rename sonic2\son2boss.htm son2boss.htm
rename sonic2\son2end.htm son2end.htm
rename sonic2\son2end2.htm son2end2.htm
rename sonic2\superson.htm superson.htm
rename sonic2\wingfort.htm wingfort.htm
rename sonic3k\angel_1.mid angel_1.mid
rename sonic3k\angel_2.mid angel_2.mid
rename sonic3k\azure_l.mid azure_l.mid
rename sonic3k\b_park.mid b_park.mid
rename sonic3k\battery1.mid battery1.mid
rename sonic3k\battery2.mid battery2.mid
rename sonic3k\bonus1.mid bonus1.mid
rename sonic3k\bonus2.mid bonus2.mid
rename sonic3k\bonus3.mid bonus3.mid
rename sonic3k\carniva2.mid carniva2.mid
rename sonic3k\carnival.mid carnival.mid
rename sonic3k\chrome_g.mid chrome_g.mid
rename sonic3k\d_palace.mid d_palace.mid
rename sonic3k\deathe_1.mid deathe_1.mid
rename sonic3k\deathe_2.mid deathe_2.mid
rename sonic3k\doomsday.mid doomsday.mid
rename sonic3k\endlessm.mid endlessm.mid
rename sonic3k\h_palace.mid h_palace.mid
rename sonic3k\hydro_1.mid hydro_1.mid
rename sonic3k\hydro_2.mid hydro_2.mid
rename sonic3k\icecap.mid icecap.mid
rename sonic3k\icecap2.mid icecap2.mid
rename sonic3k\knuckles.mid knuckles.mid
rename sonic3k\l_base1.mid l_base1.mid
rename sonic3k\l_base2.mid l_base2.mid
rename sonic3k\lavareef.mid lavareef.mid
rename sonic3k\mgardn_2.mid mgardn_2.mid
rename sonic3k\mushhill.mid mushhill.mid
rename sonic3k\mushhil2.mid mushhil2.mid
rename sonic3k\mgardn_1.mid mgardn_1.mid
rename sonic3k\robotnik.mid robotnik.mid
rename sonic3k\s-k_end.mid s-k_end.mid
rename sonic3k\s3_ss.mid s3_ss.mid
rename sonic3k\sand_1.mid sand_1.mid
rename sonic3k\sand_2.mid sand_2.mid
rename sonic3k\select.mid select.mid
rename sonic3k\sky_s.mid sky_s.mid
rename sonic3k\son3end.mid son3end.mid
rename sonic3k\act1boss.mid act1boss.mid
rename sonic3k\sound1.mid sound1.mid
rename sonic3k\angel_1.htm angel_1.htm
rename sonic3k\angel_2.htm angel_2.htm
rename sonic3k\azure_l.htm azure_l.htm
rename sonic3k\b_park.htm b_park.htm
rename sonic3k\battery1.htm battery1.htm
rename sonic3k\battery2.htm battery2.htm
rename sonic3k\bonus1.htm bonus1.htm
rename sonic3k\bonus2.htm bonus2.htm
rename sonic3k\bonus3.htm bonus3.htm
rename sonic3k\carniva2.htm carniva2.htm
rename sonic3k\carnival.htm carnival.htm
rename sonic3k\chrome_g.htm chrome_g.htm
rename sonic3k\d_palace.htm d_palace.htm
rename sonic3k\deathe_1.htm deathe_1.htm
rename sonic3k\deathe_2.htm deathe_2.htm
rename sonic3k\doomsday.htm doomsday.htm
rename sonic3k\endlessm.htm endlessm.htm
rename sonic3k\h_palace.htm h_palace.htm
rename sonic3k\hydro_1.htm hydro_1.htm
rename sonic3k\hydro_2.htm hydro_2.htm
rename sonic3k\icecap.htm icecap.htm
rename sonic3k\icecap2.htm icecap2.htm
rename sonic3k\knuckles.htm knuckles.htm
rename sonic3k\l_base1.htm l_base1.htm
rename sonic3k\l_base2.htm l_base2.htm
rename sonic3k\lavareef.htm lavareef.htm
rename sonic3k\mgardn_2.htm mgardn_2.htm
rename sonic3k\mushhill.htm mushhill.htm
rename sonic3k\mushhil2.htm mushhil2.htm
rename sonic3k\mgardn_1.htm mgardn_1.htm
rename sonic3k\robotnik.htm robotnik.htm
rename sonic3k\s-k_end.htm s-k_end.htm
rename sonic3k\s3_ss.htm s3_ss.htm
rename sonic3k\sand_1.htm sand_1.htm
rename sonic3k\sand_2.htm sand_2.htm
rename sonic3k\select.htm select.htm
rename sonic3k\sky_s.htm sky_s.htm
rename sonic3k\son3end.htm son3end.htm
rename sonic3k\act1boss.htm act1boss.htm


